# Local Lefthook configuration that uses Docker
# This allows git hooks to work with Docker-based dependencies

pre-commit:
  parallel: false
  commands:
    docker-rubocop:
      run: docker-compose run --rm app bundle exec rubocop {staged_files}
      glob: "*.rb"
      skip:
        - merge
        - rebase
      fail_text: "RuboCop found issues. Run 'make lint-fix' to auto-fix."

    check-docker:
      run: |
        if ! docker info > /dev/null 2>&1; then
          echo "Docker is not running. Please start Docker to run pre-commit hooks."
          exit 1
        fi

pre-push:
  commands:
    docker-lint-all:
      run: make lint
      fail_text: "Linting failed. Fix issues before pushing."

commit-msg:
  commands:
    check-commit-message:
      run: |
        pattern="^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\(.+\))?: .{1,72}$"
        if ! grep -qE "$pattern" "$1"; then
          echo "Commit message format invalid. Use: <type>(<scope>): <subject>"
          exit 1
        fi