require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'

# Project-specific exceptions
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/jwt_denylist.rb'  # Index exists in migration

Naming/MethodName:
  Exclude:
    - 'app/models/user.rb'  # Legacy isVerified column (TODO: migration needed)

# Style Configuration
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent

# Layout Configuration
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'app/services/detections/research_session_detection_service.rb'
    - 'app/services/insights/analyzers/hoarder_scorer.rb'
    - 'app/services/insights/calculators/comparison_calculator.rb'
    - 'app/services/insights/serial_openers/serial_opener_insight_generator.rb'
    - 'lib/tasks/**/*'
    - 'scripts/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

# Metrics Configuration (consolidated at bottom for clarity)

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - '*.gemspec'
    - 'scripts/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'app/services/insights/analyzers/domain_context_analyzer.rb'
    - 'app/services/insights/analyzers/hoarder_scorer.rb'
    - 'app/services/insights/calculators/comparison_calculator.rb'
    - 'app/services/insights/serial_openers/serial_opener_insight_generator.rb'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

# Metrics/AbcSize moved to consolidated section below

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/services/data_processing/data_sync_service.rb'
    - 'app/services/insights/serial_openers/serial_opener_insight_generator.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'app/services/data_processing/data_sync_service.rb'
    - 'app/services/insights/analyzers/domain_context_analyzer.rb'
    - 'app/services/insights/serial_openers/serial_opener_insight_generator.rb'

# Rails Configuration
Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - touch
    - update_column
    - update_columns
    - update_all
    - update_attribute

Rails/FilePath:
  Enabled: true
  EnforcedStyle: arguments

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
    - 'lib/tasks/**/*'

# RSpec Configuration
RSpec/ExampleLength:
  Max: 20  # Allow slightly longer examples for integration tests

RSpec/MultipleExpectations:
  Max: 6  # Allow up to 6 for integration tests checking response structure

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: have_received
  Exclude:
    - 'spec/services/detections/hoarder_detection_service_spec.rb'

RSpec/FilePath:
  Enabled: true
  CustomTransform:
    RuboCop: rubocop

RSpec/AnyInstance:
  Enabled: false  # Allow for error testing in service specs

# Metrics Configuration - Allow slightly higher complexity for business logic
Metrics/MethodLength:
  Max: 25  # Increased for complex service methods
  Exclude:
    - 'app/services/insights/analyzers/domain_context_analyzer.rb'
    - 'app/services/insights/calculators/comparison_calculator.rb'
    - 'app/services/insights/serial_openers/serial_opener_insight_generator.rb'
    - 'app/services/insights/serial_openers/serial_opener_insights_service.rb'

Metrics/AbcSize:
  Max: 30  # Increased for complex business logic
  Exclude:
    - 'app/services/insights/serial_openers/serial_opener_insight_generator.rb'
    - 'app/services/insights/serial_openers/serial_opener_insights_service.rb'

# Performance Configuration
Performance:
  Enabled: true

# Naming Configuration
Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - has_one
    - has_many

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - v1  # API versioning

# Lint Configuration
Lint/MissingSuper:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true

# Bundler Configuration
Bundler/OrderedGems:
  Enabled: true

# Additional excludes for pre-existing code
Style/MultilineBlockChain:
  Exclude:
    - 'app/services/insights/analyzers/value_ranker.rb'

RSpec/LetSetup:
  Exclude:
    - 'spec/services/insights/calculators/adaptive_threshold_calculator_spec.rb'
    - 'spec/services/insights/serial_openers/serial_opener_insights_service_spec.rb'

RSpec/ContextWording:
  Exclude:
    - 'spec/services/insights/calculators/adaptive_threshold_calculator_spec.rb'
    - 'spec/services/insights/serial_openers/serial_opener_insights_service_spec.rb'