require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'

# Project-specific exceptions
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/jwt_denylist.rb'  # Index exists in migration

Naming/MethodName:
  Exclude:
    - 'app/models/user.rb'  # Legacy isVerified column (TODO: migration needed)

# Style Configuration
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent

# Layout Configuration
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

# Metrics Configuration
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Rails Configuration
Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
    - touch
    - update_column
    - update_columns
    - update_all
    - update_attribute

Rails/FilePath:
  Enabled: true
  EnforcedStyle: arguments

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
    - 'lib/tasks/**/*'

# RSpec Configuration
RSpec/ExampleLength:
  Max: 20  # Allow slightly longer examples for integration tests

RSpec/MultipleExpectations:
  Max: 6  # Allow up to 6 for integration tests checking response structure

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: have_received

RSpec/FilePath:
  Enabled: true
  CustomTransform:
    RuboCop: rubocop

RSpec/AnyInstance:
  Enabled: false  # Allow for error testing in service specs

# Metrics Configuration - Allow slightly higher complexity for business logic
Metrics/MethodLength:
  Max: 25  # Increased for complex service methods

Metrics/AbcSize:
  Max: 30  # Increased for complex business logic

# Performance Configuration
Performance:
  Enabled: true

# Naming Configuration
Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - has_one
    - has_many

Naming/VariableNumber:
  EnforcedStyle: snake_case

# Lint Configuration
Lint/MissingSuper:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true

# Bundler Configuration
Bundler/OrderedGems:
  Enabled: true