
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
      - redis
    env_file:
      - config/env/.env.${RAILS_ENV:-development}
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - RAILS_ENV=${RAILS_ENV:-development}

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-heyho_sync_development}
    ports:
      - "${DATABASE_PORT:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  bundle_cache:
